global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Docker service discovery
  - job_name: 'docker-containers'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 30s
        port: 9090  # default port, will be overridden by labels
    relabel_configs:
      # Only scrape containers with prometheus.io/scrape=true label
      - source_labels: [__meta_docker_container_label_prometheus_io_scrape]
        action: keep
        regex: true
      
      # Use prometheus.io/path label for metrics path (default: /metrics)
      - source_labels: [__meta_docker_container_label_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      
      # Use prometheus.io/port label for port (default: 80)
      - source_labels: [__address__, __meta_docker_container_label_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      
      # Set instance label to container name
      - source_labels: [__meta_docker_container_name]
        action: replace
        target_label: instance
        regex: /(.*)
        replacement: $1
      
      # Set job label from container label or use container name
      - source_labels: [__meta_docker_container_label_prometheus_io_job]
        action: replace
        target_label: job
        regex: (.+)
      - source_labels: [__meta_docker_container_name]
        action: replace
        target_label: job
        regex: /(.*)
        replacement: docker-$1
      
      # Add container labels as metrics labels
      - regex: __meta_docker_container_label_(.+)
        action: labelmap
        replacement: container_label_$1

  # Docker daemon metrics (if enabled)
  - job_name: 'docker-daemon'
    static_configs:
      - targets: ['host.docker.internal:9323']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'sensors'
    static_configs:
      - targets: 
        - 'pico-climate-e38a2a2a.lan:80'
        - 'pico-climate-e3917228.lan:80'



